-- MySQL Script generated by MySQL Workbench
-- Fri Oct  3 22:28:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema controlescolar_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controlescolar_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlescolar_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `controlescolar_db` ;

-- -----------------------------------------------------
-- Table `controlescolar_db`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`persona` (
  `idpersona` INT(8) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido_paterno` VARCHAR(45) NULL DEFAULT NULL,
  `apellido_materno` VARCHAR(45) NULL DEFAULT NULL,
  `genero` CHAR(1) NULL DEFAULT NULL,
  `RFC` CHAR(13) NULL DEFAULT NULL,
  `dir_pais` VARCHAR(30) NULL DEFAULT NULL,
  `dir_estado` VARCHAR(30) NULL DEFAULT NULL,
  `dir_municipio` VARCHAR(30) NULL DEFAULT NULL,
  `dir_calle_num` VARCHAR(60) NULL DEFAULT NULL,
  `dir_codigo_postal` INT NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `correo` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `idPERSONAL_UNIQUE` (`idpersona` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`estadodecuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`estadodecuenta` (
  `idestadodecuenta` INT(8) NOT NULL,
  `linea` INT(8) NULL,
  `cargos` DECIMAL(10,2) NULL,
  `ingresos` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idestadodecuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`estudiante` (
  `matricula_alumno` INT(8) NOT NULL,
  `idpersona` INT(8) NOT NULL,
  `idbeca` INT(8) NULL,
  `idestadocuenta` INT(8) NOT NULL,
  PRIMARY KEY (`matricula_alumno`),
  INDEX `idpersona_idx` (`idpersona` ASC) VISIBLE,
  INDEX `fk_idbeca_idx` (`idbeca` ASC) VISIBLE,
  UNIQUE INDEX `idpersona_UNIQUE` (`idpersona` ASC) VISIBLE,
  UNIQUE INDEX `idbeca_UNIQUE` (`idbeca` ASC) VISIBLE,
  INDEX `fk_idestadodecuenta_idx` (`idestadocuenta` ASC) VISIBLE,
  CONSTRAINT `fk_idpersona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `controlescolar_db`.`persona` (`idpersona`)
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_idestadodecuenta`
    FOREIGN KEY (`idestadocuenta`)
    REFERENCES `controlescolar_db`.`estadodecuenta` (`idestadodecuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Maestro de Alumnos';


-- -----------------------------------------------------
-- Table `controlescolar_db`.`beca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`beca` (
  `idbeca` INT NOT NULL,
  `descripcion_beca` VARCHAR(45) NULL DEFAULT NULL,
  `porcentaje_beca` DECIMAL(5,0) NULL DEFAULT NULL,
  `estatus_beca` VARCHAR(1) NULL DEFAULT NULL,
  `idtipo_beca` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idbeca`),
  CONSTRAINT `fk_idbeca`
    FOREIGN KEY (`idtipo_beca`)
    REFERENCES `controlescolar_db`.`estudiante` (`idbeca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Catalogo de BECAS, estatus Activo, Baja, Congelada';


-- -----------------------------------------------------
-- Table `controlescolar_db`.`inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`inscripcion` (
  `idinscripcion` INT(8) NOT NULL COMMENT 'Folio de Inscrpcion PK',
  `fecha_inicio_inscripcion` INT(8) NULL COMMENT 'Fecha que se inicio el tramite de inscrpcion',
  `fecha_fin_inscripcion` INT(8) NULL COMMENT 'Fechad finalizo el proceso de inscrpcion',
  `motivo_inscripcion` VARCHAR(45) NULL COMMENT 'Carrera, Ciclo Escolar, Actividad Extracurricular',
  `Estatus` VARCHAR(1) NULL COMMENT 'Estatus:Iniciada, Proceso, Concluida,Cancelada',
  `matriculalumno` INT(8) NULL,
  PRIMARY KEY (`idinscripcion`),
  INDEX `fk_matriculaalumno_idx` (`matriculalumno` ASC) VISIBLE,
  CONSTRAINT `fk_matriculaalumno`
    FOREIGN KEY (`matriculalumno`)
    REFERENCES `controlescolar_db`.`estudiante` (`matricula_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Inscrpciones en Proceso';


-- -----------------------------------------------------
-- Table `controlescolar_db`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`pago` (
  `idpago` INT(8) NOT NULL,
  `fecha_pago` INT(8) NULL,
  `hora_pago` INT(6) NULL,
  `forma_pago` VARCHAR(45) NULL COMMENT 'Efectivo, Transferencia, Cheque',
  `idinscripcion` INT(8) NOT NULL COMMENT 'Folio de inscripción FK',
  `importe_pago` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_idinscrpcion_idx` (`idinscripcion` ASC) VISIBLE,
  UNIQUE INDEX `idinscripcion_UNIQUE` (`idinscripcion` ASC) VISIBLE,
  CONSTRAINT `fk_idinscrpcion`
    FOREIGN KEY (`idinscripcion`)
    REFERENCES `controlescolar_db`.`inscripcion` (`idinscripcion`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`departamentoacademico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`departamentoacademico` (
  `iddepartamentoacademico` INT(8) NOT NULL,
  `descrpcipcion_depto` VARCHAR(45) NULL,
  PRIMARY KEY (`iddepartamentoacademico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`carrera` (
  `idcarrera` INT(6) NOT NULL,
  `descripcion_carrera` VARCHAR(45) NULL,
  `creditos_carrera` INT(6) NULL,
  `iddepartamentoacademico` INT(8) NOT NULL,
  `costo_inscripcion` DECIMAL(10,2) NULL COMMENT 'costo de inscrpcion por periodo escolar',
  PRIMARY KEY (`idcarrera`),
  UNIQUE INDEX `iddepartamentoacademico_UNIQUE` (`iddepartamentoacademico` ASC) VISIBLE,
  CONSTRAINT `fk_iddepartamentoacademico`
    FOREIGN KEY (`iddepartamentoacademico`)
    REFERENCES `controlescolar_db`.`departamentoacademico` (`iddepartamentoacademico`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`inscripcionxcarrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`inscripcionxcarrera` (
  `idinscripcion` INT(8) NOT NULL COMMENT 'idinscripcion de los folios de inscripcion',
  `idcarrera` INT(8) NOT NULL COMMENT 'idcarrera del catalogo de carreras',
  `costo_inscripcion` DECIMAL(10,2) NULL COMMENT 'Costo de la inscrpción al ciclo escolar',
  `inscripcionxcarreracol` VARCHAR(45) NULL,
  PRIMARY KEY (`idinscripcion`, `idcarrera`),
  INDEX `fk_idcarrera_idx` (`idcarrera` ASC) VISIBLE,
  UNIQUE INDEX `idinscripcion_UNIQUE` (`idinscripcion` ASC) VISIBLE,
  CONSTRAINT `fk_inscripcionxcarrera_inscripcion`
    FOREIGN KEY (`idinscripcion`)
    REFERENCES `controlescolar_db`.`inscripcion` (`idinscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idcarrera`
    FOREIGN KEY (`idcarrera`)
    REFERENCES `controlescolar_db`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`asignatura` (
  `idasignatura` INT(8) NOT NULL,
  `descripcion_asignatura` VARCHAR(45) NULL,
  `creditos_asignatura` INT(6) NOT NULL COMMENT 'Creditos asignados a la asignatura',
  `horas_por_sesion` DECIMAL(4,2) NULL,
  PRIMARY KEY (`idasignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`asignaturaxcarrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`asignaturaxcarrera` (
  `idcarrera` INT(8) NOT NULL COMMENT 'fk identificador de carrera ',
  `idasignatura` INT(8) NOT NULL COMMENT 'identificador de asignatura',
  `departamento_academico` INT(4) NULL,
  PRIMARY KEY (`idcarrera`, `idasignatura`),
  UNIQUE INDEX `idcarrera_UNIQUE` (`idcarrera` ASC) VISIBLE,
  UNIQUE INDEX `idasignatura_UNIQUE` (`idasignatura` ASC) VISIBLE,
  CONSTRAINT `fk_idcarrera`
    FOREIGN KEY (`idcarrera`)
    REFERENCES `controlescolar_db`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idasignatura`
    FOREIGN KEY (`idasignatura`)
    REFERENCES `controlescolar_db`.`asignatura` (`idasignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`prerequisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`prerequisitos` (
  `idasignatura` INT(8) NOT NULL COMMENT 'Identificador de Asignatura',
  `asignatura_prerequisto` INT(8) NOT NULL COMMENT 'Prerequisito de Asignatura',
  PRIMARY KEY (`idasignatura`, `asignatura_prerequisto`),
  CONSTRAINT `fk_idasignatura`
    FOREIGN KEY ()
    REFERENCES `controlescolar_db`.`asignatura` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`departamentorh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`departamentorh` (
  `iddepartamentorh` INT(4) NOT NULL COMMENT 'Depratamento Recursos Humanos',
  `descripcion_departamento` VARCHAR(45) NULL COMMENT 'Descripcion departamento de Recursos Humanos',
  PRIMARY KEY (`iddepartamentorh`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`administrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`administrativo` (
  `idadministrativo` INT(8) NOT NULL COMMENT 'Identiificador Adminsitrativo',
  `iddepartamentorh` INT(4) NOT NULL COMMENT 'Departamento de Recurusos Humanos',
  `idpersona` INT(8) NOT NULL COMMENT 'fk identificador de personal',
  `fecha_contratación` INT(8) NULL,
  `fecha_baja` INT(8) NULL,
  `Estatus` VARCHAR(1) NULL COMMENT 'Estatus Activo,Baja',
  PRIMARY KEY (`idadministrativo`),
  UNIQUE INDEX `idadministrativo_UNIQUE` (`idadministrativo` ASC) VISIBLE,
  UNIQUE INDEX `iddepartamento_rh_UNIQUE` (`iddepartamentorh` ASC) VISIBLE,
  UNIQUE INDEX `idpersonal_UNIQUE` (`idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_idpersona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `controlescolar_db`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departamentorh`
    FOREIGN KEY (`iddepartamentorh`)
    REFERENCES `controlescolar_db`.`departamentorh` (`iddepartamentorh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`libro` (
  `idlibro` INT(8) NOT NULL,
  `descripcion_libro` VARCHAR(45) NULL,
  PRIMARY KEY (`idlibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`prestamo` (
  `idprestamo` INT(8) NOT NULL COMMENT 'Folio de prestamo',
  `idlibro` VARCHAR(45) NOT NULL COMMENT 'Identificador de libro',
  `idpersona` INT(8) NOT NULL,
  `fecha_prestamo` INT(8) NULL,
  `fechas_programda_entrega` INT(8) NULL,
  `fecha_devolucion` INT(8) NULL,
  `estatus_prestamo` VARCHAR(1) NULL COMMENT 'Prestado, Devuelto',
  `notas_prestamo` VARCHAR(45) NULL COMMENT 'Notas al prestamo',
  `prestamo_finalizado` VARCHAR(1) NULL COMMENT 'Si, No, Perdida de libro',
  PRIMARY KEY (`idprestamo`),
  UNIQUE INDEX `idprestamo_UNIQUE` (`idprestamo` ASC) VISIBLE,
  INDEX `fk_idpersona_idx` (`idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_idlibro`
    FOREIGN KEY ()
    REFERENCES `controlescolar_db`.`libro` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idpersona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `controlescolar_db`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`periodoinscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`periodoinscripciones` (
  `idperiodoinscripciones` INT(8) NOT NULL,
  `descripcion_periodo` VARCHAR(45) NULL,
  `fecha_inicio_insc` INT(8) NULL,
  `fecha_fin_insc` INT(8) NULL,
  `estatus` VARCHAR(1) NULL COMMENT 'Abierto/Cerrado',
  `costo_por_credito` DECIMAL(10,2) NULL COMMENT 'Costo por cada credito que tenga una asignatura',
  PRIMARY KEY (`idperiodoinscripciones`),
  UNIQUE INDEX `idperiodoinscripciones_UNIQUE` (`idperiodoinscripciones` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`modalidadenseñaza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`modalidadenseñaza` (
  `idmodalidadenseñaza` INT(8) NOT NULL,
  `descripcion_modalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idmodalidadenseñaza`),
  UNIQUE INDEX `idmodalidadenseñaza_UNIQUE` (`idmodalidadenseñaza` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`horario` (
  `idhorario` INT(4) NOT NULL,
  `descripcion_horario` VARCHAR(45) NULL,
  `horainiciolun` INT(4) NULL COMMENT 'hora de inicio HH:MM lunes',
  `horafinlun` INT(4) NULL COMMENT 'Hora Fin HH:MM Lunes',
  `horainiciomar` INT(4) NULL COMMENT 'Hora Fin Martes',
  `horafinmar` INT(4) NULL COMMENT 'Hora Fin Martes',
  `horainiciomiercoles` INT(4) NULL,
  `horafinmiercoles` INT(4) NULL COMMENT 'hora fin miercoles HH:MM',
  `horainiciojueves` INT(4) NULL COMMENT 'Hora Inicio Jueves',
  `horafinjueves` INT(4) NULL,
  `horainicioviernes` INT(4) NULL COMMENT 'HORA INICIO',
  `horafinviernes` INT(4) NULL,
  `horainiciosabado` INT(4) NULL,
  `horafinsabado` INT(4) NULL,
  `horainiciodomingo` INT(4) NULL,
  `horafindominfo` INT(4) NULL,
  PRIMARY KEY (`idhorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`docente` (
  `iddocente` INT(8) NOT NULL,
  `fecha_alta` INT(8) NULL,
  `fecha_baja` INT(8) NULL,
  `Estatus` VARCHAR(1) NULL COMMENT 'Estatus Activo, Baja',
  `idpersona` INT(8) NULL,
  PRIMARY KEY (`iddocente`),
  UNIQUE INDEX `iddocente_UNIQUE` (`iddocente` ASC) VISIBLE,
  INDEX `fk_idpersona_idx` (`idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_idpersona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `controlescolar_db`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`calendarioescolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`calendarioescolar` (
  `idcalendarioescolar` INT(8) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `fechahora` DATETIME NULL,
  PRIMARY KEY (`idcalendarioescolar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`aula` (
  `idaula` INT(4) NOT NULL,
  `descripcion_aula` VARCHAR(45) NULL,
  `lugar_fisico` VARCHAR(45) NULL COMMENT 'Localizacion de aula',
  `capacidad` INT(4) NULL,
  PRIMARY KEY (`idaula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`claseprogramada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`claseprogramada` (
  `idclaseprogramada` INT(8) NOT NULL,
  `idasignatura` INT(8) NOT NULL,
  `idmodalidadenseñanza` INT(8) NOT NULL,
  `idhorario` INT(4) NOT NULL COMMENT 'fk Identificador Horario ',
  `idioma` INT(4) NOT NULL COMMENT 'ESP,ING,FRA',
  `iddocente` INT(8) NOT NULL,
  `idperiodoinscripciones` INT(8) NOT NULL,
  `idcalendarioescolar` INT(8) NOT NULL,
  `claseprogramadacol` VARCHAR(45) NOT NULL,
  `idaula` INT(4) NOT NULL COMMENT 'Identificador de Aula fk',
  PRIMARY KEY (`idclaseprogramada`),
  UNIQUE INDEX `idclaseprogramada_UNIQUE` (`idclaseprogramada` ASC) VISIBLE,
  INDEX `fk_idasignatura_idx` (`idasignatura` ASC) VISIBLE,
  INDEX `fk_modalidadenseñanza_idx` (`idmodalidadenseñanza` ASC) VISIBLE,
  INDEX `fk_idhorario_idx` (`idhorario` ASC) VISIBLE,
  INDEX `fk_idcalendarioescolar_idx` (`idcalendarioescolar` ASC) VISIBLE,
  INDEX `fk_idaula_idx` (`idaula` ASC) VISIBLE,
  CONSTRAINT `fk_idasignatura`
    FOREIGN KEY (`idasignatura`)
    REFERENCES `controlescolar_db`.`asignatura` (`idasignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modalidadenseñanza`
    FOREIGN KEY (`idmodalidadenseñanza`)
    REFERENCES `controlescolar_db`.`modalidadenseñaza` (`idmodalidadenseñaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idhorario`
    FOREIGN KEY (`idhorario`)
    REFERENCES `controlescolar_db`.`horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_iddocente`
    FOREIGN KEY ()
    REFERENCES `controlescolar_db`.`docente` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idperiodoinscripciones`
    FOREIGN KEY ()
    REFERENCES `controlescolar_db`.`periodoinscripciones` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idcalendarioescolar`
    FOREIGN KEY (`idcalendarioescolar`)
    REFERENCES `controlescolar_db`.`calendarioescolar` (`idcalendarioescolar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idaula`
    FOREIGN KEY (`idaula`)
    REFERENCES `controlescolar_db`.`aula` (`idaula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`certificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`certificacion` (
  `idcertificacion` INT(8) NOT NULL,
  `decripcion` VARCHAR(45) NULL,
  `institucion` VARCHAR(45) NULL,
  `fecha_certificacion` INT(8) NULL,
  PRIMARY KEY (`idcertificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`capacitacion` (
  `idcapacitacion` INT(8) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha_inicio` INT(8) NULL,
  `fecha_fin` INT(8) NULL,
  `horas_capacitacion` DECIMAL(4,2) NULL COMMENT 'Horas de capaciton con fracciones de hora',
  `institucion` VARCHAR(45) NULL,
  PRIMARY KEY (`idcapacitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`docentecertificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`docentecertificacion` (
  `iddocente` INT(8) NOT NULL,
  `idcertificacion` INT(8) NOT NULL,
  PRIMARY KEY (`iddocente`, `idcertificacion`),
  INDEX `idcertificacion_idx` (`idcertificacion` ASC) VISIBLE,
  CONSTRAINT `iddocente`
    FOREIGN KEY (`iddocente`)
    REFERENCES `controlescolar_db`.`docente` (`iddocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcertificacion`
    FOREIGN KEY (`idcertificacion`)
    REFERENCES `controlescolar_db`.`certificacion` (`idcertificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`docentecapacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`docentecapacitacion` (
  `iddocente` INT(8) NOT NULL,
  `idcapacitacion` INT(8) NOT NULL,
  PRIMARY KEY (`iddocente`, `idcapacitacion`),
  INDEX `fk_idcapacitacion_idx` (`idcapacitacion` ASC) VISIBLE,
  CONSTRAINT `fk_iddocente`
    FOREIGN KEY (`iddocente`)
    REFERENCES `controlescolar_db`.`docente` (`iddocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idcapacitacion`
    FOREIGN KEY (`idcapacitacion`)
    REFERENCES `controlescolar_db`.`capacitacion` (`idcapacitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`inscripcion_claseprogramada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`inscripcion_claseprogramada` (
  `idinscrpcion` INT(8) NOT NULL,
  `idclaseprogramada` INT(8) NOT NULL,
  `asistencia` DECIMAL(5,2) NULL COMMENT 'Asistencia porcentaje de asistencia en el curso',
  PRIMARY KEY (`idinscrpcion`, `idclaseprogramada`),
  INDEX `fk_idclaseprogramada_idx` (`idclaseprogramada` ASC) VISIBLE,
  CONSTRAINT `fk_idinscripcion`
    FOREIGN KEY (`idinscrpcion`)
    REFERENCES `controlescolar_db`.`inscripcion` (`idinscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idclaseprogramada`
    FOREIGN KEY (`idclaseprogramada`)
    REFERENCES `controlescolar_db`.`claseprogramada` (`idclaseprogramada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`evaluacion` (
  `idevaluacion` INT(8) NOT NULL,
  `tipo_actividad_academica` ENUM('TAREA', 'EXAMEN', 'ACTIVIDAD') NULL,
  `descrpcion` VARCHAR(45) NULL,
  `calificacion` DECIMAL(4,2) NULL,
  `idclaseprogramada` INT(8) NULL,
  PRIMARY KEY (`idevaluacion`),
  INDEX `fk_idclaseprograma_idx` (`idclaseprogramada` ASC) VISIBLE,
  CONSTRAINT `fk_idclaseprograma`
    FOREIGN KEY (`idclaseprogramada`)
    REFERENCES `controlescolar_db`.`inscripcion_claseprogramada` (`idinscrpcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlescolar_db`.`historialacademica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlescolar_db`.`historialacademica` (
  `idhistorialacademica` INT(8) NOT NULL,
  `idevaluacion` INT(8) NOT NULL,
  `idestudiante` INT(8) NULL,
  PRIMARY KEY (`idhistorialacademica`, `idevaluacion`),
  INDEX `fk_idevaluacion_idx` (`idevaluacion` ASC) VISIBLE,
  CONSTRAINT `fk_idevaluacion`
    FOREIGN KEY (`idevaluacion`)
    REFERENCES `controlescolar_db`.`evaluacion` (`idevaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
